### ISSUE TITLE
Interrupted system call causes client exit

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/radiopadre-client#12]
Suddenly (1.0rc6), this happens:
```
Traceback (most recent call last):
  File "/home/oms/radiopadre-client/radiopadre_client/remote.py", line 337, in run_remote_session                                         
    fdlist = poller.poll()
  File "/home/oms/radiopadre-client/iglesia/utils.py", line 128, in poll
    to_read, _, _ = select.select(self.fdlabels.keys(), [], [], timeout)
error: (4, 'Interrupted system call')
radiopadre.client [28.66s]: Exception caught: (4, 'Interrupted system call')
radiopadre.client [28.66s]: Asking remote session to exit, nicely
```
Not sure what causes the signal (child process i.e. browser exiting perhaps?) and I can't recreate reliably, but in any case``poll()`` needs to be called again on this error, this I should know from childhood.

**Comment by o-smirnov** [comment]
Seems to be a py2 problem only. Can be recreated by resizing terminal (doesn't cause a select.select() exception in py3, the library must handle it internally).

Note that, annoyingly, the 2.7 version of select throws a ``select.error``, while the py3 libraries throw the more standard  ``IOError``.
