### ISSUE TITLE
Add environment variable for searching image file location

### ISSUE THREAD

**Issue by smasoka** [ratt-ru/radiopadre-client#26]
`radiopadre-client` searches for the image under user home directories `/home/username/.radiopadre/`
For situations where the image is located elsewhere, it would be good to have an environment variable to specify a search location.

**Comment by smasoka** [comment]
Environment variable `RADIOPADRE_SINGULARITY_IMAGE_DIR` is not being picked up. I can't seem to make it work. 

caracal version 1.0.2

```console
2020-05-27 12:16:32 CARACal INFO: Rendering report(s)
# running run-radiopadre --non-interactive --singularity --update --nbconvert output/simple_caracal-detailed-final-report.ipynb
# which: no docker in (/usr/local/apps/singularity/3.5.3/bin:/apps/chpc/astro/anaconda3/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/3.2.10/bin:/opt/pbs/bin:/opt/dell/srvadmin/bin:/home/smasoka/.local/bin:/home/smasoka/bin)
# INFO:    Starting build...
# FATAL:   While performing build: conveyor failed to get: pinging docker registry returned: Get https://registry-1.docker.io/v2/: dial tcp 18.232.227.119:443: i/o timeout
# Traceback (most recent call last):
#   File "/apps/chpc/astro/anaconda3/bin/run-radiopadre", line 326, in <module>
#     radiopadre_client.server.run_radiopadre_server(command, arguments, notebook_path, workdir=options.workdir)
#   File "/apps/chpc/astro/anaconda3/lib/python3.7/site-packages/radiopadre_client/server.py", line 297, in run_radiopadre_server
#     backend.update_installation()
#   File "/apps/chpc/astro/anaconda3/lib/python3.7/site-packages/radiopadre_client/backends/singularity.py", line 105, in update_installation
#     subprocess.check_call(cmd)
#   File "/apps/chpc/astro/anaconda3/lib/python3.7/subprocess.py", line 363, in check_call
#     raise CalledProcessError(retcode, cmd)
# subprocess.CalledProcessError: Command '['/usr/local/apps/singularity/3.5.3/bin/singularity', 'build', '/apps/chpc/astro/stimela_images/osmirnov_radiopadre:1.0pre12.singularity.img.new.img', 'docker://osmirnov/radiopadre:1.0pre12']' returned non-zero exit status 255.
2020-05-27 12:17:32 CARACal WARNING: Report output/simple_caracal-detailed-final-report.html failed to render (run-radiopadre returns error code 1). HTML report will not be available.
2020-05-27 12:17:32 CARACal WARNING: Report output/simple_caracal-detailed-final-report.html failed to render
[smasoka@cnode0974 caracal_testing]$ env|grep RADIO
RADIOPADRE_SINGULARITY_IMAGE_DIR=/apps/chpc/astro/stimela_images
[smasoka@cnode0974 caracal_testing]$ ls $RADIOPADRE_SINGULARITY_IMAGE_DIR/radiopadre*
/apps/chpc/astro/stimela_images/radiopadre_1.0pre10.sif   /apps/chpc/astro/stimela_images/radiopadre_1.0pre12.sif
/apps/chpc/astro/stimela_images/radiopadre-1.0pre10.simg
[smasoka@cnode0974 caracal_testing]$
```

**Comment by o-smirnov** [comment]
But it is being picked up, see this line, the correct path is in there:
```
# subprocess.CalledProcessError: Command '['/usr/local/apps/singularity/3.5.3/bin/singularity', 'build', '/apps/chpc/astro/stimela_images/osmirnov_radiopadre:1.0pre12.singularity.img.new.img', 'docker://osmirnov/radiopadre:1.0pre12']' returned non-zero exit status 255.
```
I think the problem is, it's being invoked with ``-u``, so tries to initiate a pull anyway, and fails. Can you take out the ``-u`` from the invocation in caracal just to see if it fixes things?
