### ISSUE TITLE
unhelpful error message from client 1.2 when remote has an older version installed

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/radiopadre-client#52]
As reported by Kenda: 

After upgrading, I'm getting an error when running radiopadre from my local

```
$ run-radiopadre -V oates:/scratch/knowles/output-jwstu/jwst0723u-std-progress-report.ipynb --auto-init
radiopadre.client [0.02s]: Welcome to the radiopadre client release 1.2.0!
radiopadre.client [0.02s]:   command line specifies AUTO_INIT = True
radiopadre.client [0.02s]:   command line specifies BACKEND = venv
radiopadre.client: Opening ssh connection to oates. You may be prompted for your password.
radiopadre.client: Using remote client script within /home/knowles/.radiopadre/venv
radiopadre.client: running radiopadre client on oates
radiopadre.client: oates: radiopadre.client [0.01s]: Welcome to the radiopadre client pre-release 1.2.pre2!
radiopadre.client: oates: radiopadre.client: Starting new session in virtual environment
radiopadre.client: oates: radiopadre.client:   Selected ports: 1024:1025:1026:1033:1034:1035:13001:13002:13003:13004:13005:13006
radiopadre.client: The ssh process to oates reports EOF
Traceback (most recent call last):
  File "/home/s2100047/.local/lib/python3.8/site-packages/radiopadre_client/remote.py", line 429, in run_remote_session
    results = loop.run_until_complete(job)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/s2100047/.local/lib/python3.8/site-packages/radiopadre_client/remote.py", line 390, in remote_stream_reader
    ssh2_args += ["-L", f"localhost:{loc}:{remote_hostname}:{rem}"]
UnboundLocalError: local variable 'remote_hostname' referenced before assignment
radiopadre.client: Exception caught: local variable 'remote_hostname' referenced before assignment
radiopadre.client: Remote session has exited with return code 1
```
When I run it from inside oates, it starts a session but doesn't open up any browsers. Not sure what I've broken here.

**Comment by o-smirnov** [comment]
Should probably parse the remote "welcome" string and bomb out if versions don't match.
