### ISSUE TITLE
auto-init fails when running radiopadre

### ISSUE THREAD

**Issue by kvanqa** [ratt-ru/radiopadre-client#53]
When I initialize radiopadre to launch a browser I get this:
```
radiopadre.client [0.15s]: Welcome to the radiopadre client release 1.2.0!
radiopadre.client [0.15s]:   command line specifies AUTO_INIT = True
radiopadre.client [0.15s]:   command line specifies BACKEND = venv
radiopadre.client: Opening ssh connection to kvanqa@com12.science.kat.ac.za. You may be prompted for your password.
radiopadre.client: Remote virtualenv /home/kvanqa/.radiopadre/venv exists, but does not contain a radiopadre-client installation.
radiopadre.client: No remote client script run-radiopadre found
radiopadre.client: No run-radiopadre script found on kvanqa@com12.science.kat.ac.za
radiopadre.client: Trying to --auto-init an installation for you...
radiopadre.client: Installing into existing virtualenv kvanqa@com12.science.kat.ac.za:~/.radiopadre/venv
radiopadre.client: --client-install-path ~/radiopadre-client is configured and exists on kvanqa@com12.science.kat.ac.za.
radiopadre.client: Will attempt to pip install -U -e ~/radiopadre-client in kvanqa@com12.science.kat.ac.za:~/.radiopadre/venv
Shared connection to com12.science.kat.ac.za closed.
radiopadre.client: ssh source /home/kvanqa/.radiopadre/venv/bin/activate && pip install  -U -e ~/radiopadre-client failed with exit code 1
Traceback (most recent call last):
  File "/Users/kamvavanqa/radiop/bin/run-radiopadre", line 345, in <module>
    retcode = radiopadre_client.remote.run_remote_session(command, copy_initial_notebook, notebook_path, arguments)
  File "/Users/kamvavanqa/radiop/lib/python3.8/site-packages/radiopadre_client/remote.py", line 264, in run_remote_session
    ssh_remote_v(f"source {config.RADIOPADRE_VENV}/bin/activate && {pip_install} -U {install_path}")
  File "/Users/kamvavanqa/radiop/lib/python3.8/site-packages/radiopadre_client/remote.py", line 54, in ssh_remote_v
    return ssh_remote(command, fail_retcode, stderr=sys.stderr)
  File "/Users/kamvavanqa/radiop/lib/python3.8/site-packages/radiopadre_client/remote.py", line 46, in ssh_remote
    return subprocess.check_output(SSH_OPTS + [shlex.quote(command)], stderr=stderr).decode('utf-8')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ssh', '-t', '-t', '-o', 'ControlPath=/tmp/ssh_mux_radiopadre_%C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1h', 'kvanqa@com12.science.kat.ac.za', '/bin/bash', '-c', "'source /home/kvanqa/.radiopadre/venv/bin/activate && pip install  -U -e ~/radiopadre-client'"]' returned non-zero exit status 1.
```

**Comment by o-smirnov** [comment]
@kvanqa sorry I missed this -- are you still having this problem?

**Comment by kvanqa** [comment]
@o-smirnov Yes I'm still encountering this issue specifically on the 'com12' machine. Strangely, even when I attempt to run it on singularity/ docker, the problem persists. However, when I execute it on 'com04,' the singularity works fine, though the initial problem remains. I'm uncertain whether the issue is related to the 'com' machines or if it's specific to 'com12.' Interestingly, radiopadre launches fine on the Rhodes machines. So I had to continue on com04

**Comment by o-smirnov** [comment]
Ok I'll give it a try on com12.

**Comment by SavannahStanbury** [comment]
Was this issue ever resolved? I am having the same issue after attempting to update radiopadre.

radiopadre.client [0.02s]: Welcome to the radiopadre client release 1.2.0!
radiopadre.client [0.02s]:   command line specifies AUTO_INIT = True
radiopadre.client: Opening ssh connection to stanbury@young.ru.ac.za. You may be prompted for your password.
radiopadre.client: ssh which git failed with exit code 255
Traceback (most recent call last):
  File "/home/stanbury/.local/bin/run-radiopadre", line 345, in <module>
    retcode = radiopadre_client.remote.run_remote_session(command, copy_initial_notebook, notebook_path, arguments)
  File "/home/stanbury/.local/lib/python3.8/site-packages/radiopadre_client/remote.py", line 96, in run_remote_session
    has_git = check_remote_command("git")
  File "/home/stanbury/.local/lib/python3.8/site-packages/radiopadre_client/remote.py", line 75, in check_remote_command
    return (ssh_remote("which " + command, fail_retcode=1, stderr=DEVNULL) or "").strip()
  File "/home/stanbury/.local/lib/python3.8/site-packages/radiopadre_client/remote.py", line 46, in ssh_remote
    return subprocess.check_output(SSH_OPTS + [shlex.quote(command)], stderr=stderr).decode('utf-8')
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ssh', '-t', '-t', '-o', 'ControlPath=/tmp/ssh_mux_radiopadre_%C', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=1h', 'stanbury@young.ru.ac.za', '/bin/bash', '-c', "'which git'"]' returned non-zero exit status 255.
